"""Compile the project into a plain HTML/CSS/JS(+PHP logger) website in ``/dist/``.

Single-language project::

    dist/index.html + story.js          the story
    dist/tiltale.js, style.css, ...     shared runtime files

Multi-language project::

    dist/index.html + story.js          language-picker frames (optional)
    dist/<slug>---<language>/           one folder per language: index.html + story.js
    dist/tiltale.js, style.css, ...     shared by every page

Shared by every page: ``tiltale.js``, ``bubbles.js``, ``style.css``, ``logo-tiltale.png``,
``favicon.ico``, ``assets/`` (responsive images), ``log.php`` and ``logs/``.
Frames are identified by their fixed ID (``Frame.key``, e.g. ``fnr-12``) in everything generated.
"""

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import hashlib
from html import escape
import json
from pathlib import Path
import re
import shutil
from typing import Any

from django.conf import settings
from PIL import Image, ImageOps

from studio.models import Frame, ProjectSettings

from .components import ComponentDefinition, component_css, component_map
from .content import ContentRow, ContentTable, load_content_table
from .project import BRANDING_FILES, newest_source_timestamp, safe_child
from .validate import ValidationIssue, validate_project

IMAGE_WIDTHS: tuple[int, ...] = (480, 960, 1920)
SHARED_FILES: tuple[str, ...] = ("tiltale.js", "bubbles.js", "style.css", "logo-tiltale.png", "favicon.ico")
GENERATED_NOTE: str = "Generated by TilTale. Edit the source and press Regenerate; do not edit /dist/ by hand."


@dataclass(frozen=True, slots=True)
class Build:
    label: str
    language: str  # "" for the language-picker page
    folder: str  # "" means the /dist/ root


@dataclass(frozen=True, slots=True)
class BuildReport:
    generated_at: str
    source_timestamp: float
    builds: tuple[Build, ...]
    issues: tuple[ValidationIssue, ...]


def branding_file(name: str) -> Path:
    """The project's own logo/favicon when present in /project/, else the TilTale default."""
    override: Path = settings.PROJECT_DIR / name
    return override if override.is_file() else settings.BRANDING_DIR / name


def story_css() -> str:
    """Element, component and project CSS: everything that decides how elements look."""
    parts: list[str] = [
        (settings.RUNTIME_DIR / "elements.css").read_text(encoding="utf-8"),
        component_css(),
        (settings.PROJECT_DIR / "default-colors.css").read_text(encoding="utf-8"),
        (settings.PROJECT_DIR / "style-overrides.css").read_text(encoding="utf-8"),
    ]
    return "\n\n".join(parts)


def language_folder(project: ProjectSettings, language: str, languages: tuple[str, ...]) -> str:
    """``""`` for single-language projects, otherwise ``<slug>---<language>``."""
    if len(languages) < 2:
        return ""
    segment: str = re.sub(r"[^A-Za-z0-9._-]+", "-", language).strip("-.") or "language"
    return f"{project.slug}---{segment}"


def page_path(folder: str) -> str:
    return f"{folder}/index.html" if folder else "index.html"


def reset_dist_directory() -> None:
    """Empty ``/dist/`` but keep ``/dist/logs/`` (study data is never deleted)."""
    base: Path = settings.BASE_DIR.resolve()
    dist: Path = settings.DIST_DIR.resolve()
    project: Path = settings.PROJECT_DIR.resolve()
    if dist == base or base not in dist.parents:
        raise ValueError("DIST_DIR must be a dedicated folder inside the TilTale repository.")
    if dist == project or dist in project.parents or project in dist.parents:
        raise ValueError("Refusing to regenerate because DIST_DIR overlaps /project/.")
    dist.mkdir(exist_ok=True)
    for child in dist.iterdir():
        if child.name == "logs":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def _image_variants(relative_source: str) -> list[dict[str, Any]]:
    """Write WebP variants (never upscaled, never wider than 1920px) to dist/assets/."""
    source: Path = safe_child(settings.PROJECT_DIR / "materials", relative_source)
    if not source.is_file():
        return []
    digest: str = hashlib.sha1(relative_source.encode("utf-8")).hexdigest()[:8]
    stem: str = re.sub(r"[^A-Za-z0-9_-]+", "-", source.stem).strip("-") or "image"
    with Image.open(source) as opened:
        image: Image.Image = ImageOps.exif_transpose(opened)
        transparent: bool = "A" in image.getbands() or "transparency" in image.info
        image = image.convert("RGBA" if transparent else "RGB")
    variants: list[dict[str, Any]] = []
    for width in sorted({min(width, image.width) for width in IMAGE_WIDTHS}):
        height: int = max(1, round(image.height * width / image.width))
        destination: Path = settings.DIST_DIR / "assets" / f"{stem}-{digest}-{width}w.webp"
        image.resize((width, height), Image.Resampling.LANCZOS).save(destination, "WEBP", quality=82, method=6)
        variants.append({"width": width, "path": f"assets/{destination.name}", "bytes": destination.stat().st_size})
    return variants


def _frame_payload(
    frame: Frame,
    language: str,
    content_by_id: dict[int, ContentRow],
    components: dict[str, ComponentDefinition],
    images: dict[str, list[dict[str, Any]]],
) -> dict[str, Any]:
    background: dict[str, Any] = {"type": frame.background_type}
    if frame.background_type == Frame.BackgroundType.SOLID:
        background["color"] = frame.background_color
    elif frame.background_type == Frame.BackgroundType.IMAGE:
        background["sources"] = images.get(frame.background_image, [])
        background["box"] = frame.background_box

    elements: list[dict[str, Any]] = []
    for element in frame.elements.all():
        if element.image:
            elements.append({
                "id": element.id, "image": images.get(element.image, []),
                **element.geometry(language), "delay_mode": element.delay_mode,
            })
            continue
        component = components.get(element.component)
        if component is None:
            continue
        row = content_by_id.get(element.content_id) if element.content_id else None
        text: str = element.text if frame.is_language_picker else (row.values.get(language, "") if row else "")
        elements.append({
            "id": element.id,
            "component": component.slug,
            "content_id": element.content_id,
            "text": text if component.accepts_content else "",
            "clickable": component.clickable,
            "target": element.target_frame.key if element.target_frame else None,
            "language": element.target_language or None,
            "ends_story": element.ends_story,
            **element.geometry(language),
            "tail_x": element.tail_x,
            "tail_y": element.tail_y,
            "fill": element.fill_color,
            "border": element.border_color,
            "text_color": element.text_color,
            "break_long_words": element.break_long_words,
            "delay_mode": element.delay_mode,
        })
    return {"name": frame.key, "fade_in": frame.fade_in, "background": background, "elements": elements}


def _story_js(story: dict[str, Any]) -> str:
    return f"/* {GENERATED_NOTE} */\nvar STORY = {json.dumps(story, ensure_ascii=False, separators=(',', ':'))};\n"


def _write_page(folder: str, story: dict[str, Any], html_language: str, title: str) -> None:
    """Write index.html + story.js. ``base_bytes`` is the download size before images."""
    output: Path = settings.DIST_DIR / folder if folder else settings.DIST_DIR
    output.mkdir(exist_ok=True)
    root: str = story["root"]
    html: str = (
        (settings.RUNTIME_DIR / "index.html").read_text(encoding="utf-8")
        .replace("__LANGUAGE__", escape(html_language, quote=True))
        .replace("__TITLE__", escape(title))
        .replace("__ROOT__", root)
    )
    (output / "index.html").write_text(html, encoding="utf-8")
    shared: int = sum((settings.DIST_DIR / name).stat().st_size for name in SHARED_FILES if (settings.DIST_DIR / name).is_file())
    story["base_bytes"] = shared + len(html.encode("utf-8")) + len(_story_js(story).encode("utf-8"))
    (output / "story.js").write_text(_story_js(story), encoding="utf-8")


def _write_shared_files() -> None:
    dist: Path = settings.DIST_DIR
    runtime: Path = settings.RUNTIME_DIR
    (dist / "assets").mkdir()
    (dist / "logs").mkdir(exist_ok=True)
    (dist / "logs" / ".htaccess").write_text("Require all denied\n", encoding="utf-8")
    shutil.copy2(runtime / "log.php", dist / "log.php")
    for name in BRANDING_FILES:
        shutil.copy2(branding_file(name), dist / name)
    for name in ("tiltale.js", "bubbles.js"):
        (dist / name).write_text(f"/* {GENERATED_NOTE} */\n" + (runtime / name).read_text(encoding="utf-8"), encoding="utf-8")
    page_css: str = (runtime / "style.css").read_text(encoding="utf-8")
    (dist / "style.css").write_text(f"/* {GENERATED_NOTE} */\n\n{page_css}\n{story_css()}\n", encoding="utf-8")


def generate_dist(project: ProjectSettings) -> BuildReport:
    """Validate, then rebuild ``/dist/`` completely from the project."""
    content: ContentTable = load_content_table(settings.PROJECT_DIR / "content.xlsx")
    issues: list[ValidationIssue] = validate_project(project, content)
    components = component_map()
    languages: tuple[str, ...] = content.languages
    folders: dict[str, str] = {language: language_folder(project, language, languages) for language in languages}
    if len(set(folders.values())) != len(folders):
        raise ValueError("Two language columns would produce the same /dist/ folder name.")

    frames: list[Frame] = list(Frame.objects.prefetch_related("elements__language_overrides", "elements__target_frame"))
    story_frames: list[Frame] = [frame for frame in frames if not frame.is_language_picker]
    pickers: list[Frame] = [frame for frame in frames if frame.is_language_picker] if len(languages) > 1 else []

    reset_dist_directory()
    _write_shared_files()
    backgrounds: set[str] = {frame.background_image for frame in frames if frame.background_type == Frame.BackgroundType.IMAGE}
    pictures: set[str] = {element.image for frame in frames for element in frame.elements.all() if element.image}
    images: dict[str, list[dict[str, Any]]] = {path: _image_variants(path) for path in sorted(backgrounds | pictures)}
    content_by_id = content.by_id()

    def story(page_frames: list[Frame], language: str, root: str) -> dict[str, Any]:
        return {
            "project": project.slug,
            "language": language,
            "root": root,
            "frame_width": project.frame_width,
            "frame_height": project.frame_height,
            "letterbox_color": project.letterbox_color,
            "default_delay_seconds": float(project.default_delay_seconds),
            "participant_parameter": project.participant_parameter,
            "finish_redirect_url": project.finish_redirect_url,
            "languages": folders if not language else {},
            "start_frame": page_frames[0].key if page_frames else None,
            "components": {
                slug: {"svg": component.svg, "auto_height": component.auto_height, "tail": component.tail}
                for slug, component in components.items()
            },
            "frames": [_frame_payload(frame, language, content_by_id, components, images) for frame in page_frames],
        }

    builds: list[Build] = []
    for language in languages:
        folder: str = folders[language]
        _write_page(folder, story(story_frames, language, "../" if folder else ""), language, project.name)
        builds.append(Build(label=language, language=language, folder=folder))
    if pickers:
        _write_page("", story(pickers, "", ""), project.base_language, project.name)
        builds.insert(0, Build(label="Language picker", language="", folder=""))

    report = BuildReport(
        generated_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        source_timestamp=newest_source_timestamp(),
        builds=tuple(builds),
        issues=tuple(issues),
    )
    (settings.DIST_DIR / ".build.json").write_text(json.dumps(asdict(report), indent=2), encoding="utf-8")
    return report


def load_build_report() -> dict[str, Any] | None:
    try:
        value: Any = json.loads((settings.DIST_DIR / ".build.json").read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def dist_is_stale() -> bool:
    report = load_build_report()
    try:
        return newest_source_timestamp() > float(report["source_timestamp"]) + 0.001  # type: ignore[index]
    except (KeyError, TypeError, ValueError):
        return True
