# Generated by Django 6.1.1 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='frame',
            name='background_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='background_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='background_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='background_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
