# Generated by Django 6.1.1 on 2026-09-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_element_image_frame_background_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='tail_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='tail_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
