# Generated by Django 6.1.1 on 2026-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_element_tail_x_element_tail_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='close_content_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='zoomable',
            field=models.BooleanField(default=False),
        ),
    ]
