# Generated by Django 6.1.1 on 2026-09-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_frame_close_content_id_frame_zoomable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='element',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
