# Generated by Django 6.1.1 on 2026-09-15 08:23, with one hand-written step (convert_existing_frames),
# because the old is_language_picker/zoomable flags become Frame.kind and a document's single image
# element becomes its background image. TilTale 2.1: no compatibility with older projects is kept.

import django.db.models.deletion
from django.db import migrations, models


def convert_existing_frames(apps, schema_editor):
    Frame = apps.get_model("studio", "Frame")
    Element = apps.get_model("studio", "Element")
    Frame.objects.filter(is_language_picker=True).update(kind="picker")
    for frame in Frame.objects.filter(zoomable=True):
        image = Element.objects.filter(frame=frame).exclude(image="").first()
        frame.kind = "document"
        if image is not None:
            frame.background_type, frame.background_image = "image", image.image
        frame.save(update_fields=["kind", "background_type", "background_image"])
        Element.objects.filter(frame=frame).delete()  # a document is its image only
    Element.objects.update(break_long_words=False)  # 2.1 stops breaking long words unless an author asks for it


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_element_options_element_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('initial_value', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='hidden_on',
            field=models.ManyToManyField(blank=True, related_name='hidden_global_elements', to='studio.frame'),
        ),
        migrations.AddField(
            model_name='element',
            name='restarts_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='element',
            name='update_operation',
            field=models.CharField(default='set', max_length=3),
        ),
        migrations.AddField(
            model_name='element',
            name='update_value',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frame',
            name='kind',
            field=models.CharField(choices=[('frame', 'Frame'), ('picker', 'Picker'), ('document', 'Document'), ('validation', 'Validation point'), ('minigame', 'Minigame')], default='frame', max_length=12),
        ),
        migrations.RunPython(convert_existing_frames, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='frame',
            name='is_language_picker',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='zoomable',
        ),
        migrations.AlterField(
            model_name='element',
            name='break_long_words',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='studio.frame'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('comparator', models.CharField(default='==', max_length=2)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='studio.frame')),
                ('target_frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_rules', to='studio.frame')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='studio.variable')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='element',
            name='update_variable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updates', to='studio.variable'),
        ),
    ]
