# Generated by Django 6.1.1 on 2026-09-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_frame_kinds_variables_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='log_key_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='log_key_pending',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='log_public_key',
            field=models.TextField(blank=True, default=''),
        ),
    ]
