# Generated by Django 6.1.1 on 2026-09-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_log_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='fade_from_black',
            field=models.BooleanField(default=False),
        ),
    ]
